### ISSUE TITLE
Unable to find IP address

### ISSUE THREAD

**Issue by DuelistRag3** [Lan2Play/eventula-manager#878] opened 2024-10-23 19:08 UTC
So when i follow the tutorial from the docs i get the following error:
```
error="service \"myservice\" error: unable to find IP address for the container \"/eventula_manager_app/": the server is ingored
```
with portainer i observed that the app service does not join bridge network nor getting an ip address in the eventula_default

**Comment by Apfelwurm** [comment] 2024-10-24 08:00
Hey, at first, i have never used portainer, so i currently don't know the specifics of it.
Please provide more information, so we can find out what is wrong.
How did you set up eventula in portainer step by step? 
What is myservice?
What bridge network are you talking about? (the eventula container is not built to be directly exposed to the internet, even though it should be possible, but not recommended)
Is your machine online or offline?
how does your compose (if used) look like?
how does your env look like? (ofc with replaced passwords)
what is the eventula container logging?
how long did you wait after the startup?

Have a great day!

PS: Maybe consider joining our Discord (https://discord.gg/zF5C9WPWFq) for a more direct support experience

**Comment by DuelistRag3** [comment] 2024-10-24 10:48
Hi,
to be more clear, for the setup of eventula itself i used the compose and .env file from your documentation via the commandline of a freshly setup ubuntu VM. I use Portainer ( A GUI tool for Docker containers) as a monitorung tool.

Myservice comes from a line from ur compose file:
```
services:
    app:
        image: lan2play/eventula-manager:latest
        restart: unless-stopped
        volumes:
        - eventula_manager_storage:/web/html/storage/
        expose:
        - "80"
        env_file:
        - ./.env
        container_name: eventula_manager_app
        labels:
        - "com.centurylinklabs.watchtower.scope=ev01"
        - "traefik.enable=true"
        - "traefik.http.routers.ev01.rule=Host(`${APP_URL}`)"
        - "traefik.http.routers.ev01.entrypoints=websecure"
        - "traefik.http.routers.ev01.tls.certresolver=le"
        - "traefik.http.services.myservice.loadbalancer.server.port=80"
```
**- "traefik.http.services._myservice_.loadbalancer.server.port=80"**

its an online machine.

I think its still try to boot, if im not wrong, i didn´t canceled it.
I´ll check the logs in a minute.

Best regards
Christian

**Comment by Apfelwurm** [comment] 2024-10-24 11:01
Hi Christian,
thanks for the additional infos!
My bad, had not in mind that i called that service myservice in our traefik example, cause currently in our prod setup, we don't use traefik because our instance is integrated into our existing reverse proxy environment. But looking over it, it might be possible that it does not work because traefik v3 was released since i wrote that compose file, so there might be labels or mechanisms that changed since then. Going to test that later today and going to give you an update as soon as i get to it. Checking the logs of the eventula container is a good idea never the less :)

Alex

**Comment by DuelistRag3** [comment] 2024-10-24 11:14
Here are the logs
[logs.txt](https://github.com/user-attachments/files/17505901/logs.txt)

**Comment by DuelistRag3** [comment] 2024-10-24 11:26
![image](https://github.com/user-attachments/assets/ea4d2cb8-9c1e-4945-84c9-0ed7cf19c39e)
As u can see here (thats my portainer gui) the app and the database do not get an internel IP-Address

**Comment by DuelistRag3** [comment] 2024-10-24 11:28
Ok, just discovered they bootlop, thats why they don´t get an ip address

**Comment by DuelistRag3** [comment] 2024-10-24 12:44
Kleine Randnotiz, ich habe es jetzt ebenfalls zum Laufen bekommen indem ich Eventula Plain in meine bestehenden Systeme (MariaDB und Reverse Proxy) eingebunden habe, der Issue sollte trotzdem zu ende  untersucht werden, für Leute die vielleicht kein bestehenden Proxy ETC. haben.

So, back to english, i will do a test run later that day and look at all logs in particular

**Comment by Apfelwurm** [comment] 2024-10-24 18:17
When testing the current state, i sadly cannot reproduce that problem when following our documentation. The error you had `ERR error="service \"myservice\" error: unable to find the IP address for the container \"/eventula_manager_app\": the server is ignored" container=app-eventula-db62bd90f76806e891c711ab9359d3fda41446ed4cac58d465405590519e9147 providerName=docker
` 
is to be expected a few times until the database is working, but disappears as soon as the seeding took place.

I'm glad you managed to get it running :)
Sadly the part of your log you provided above is not enough to see anything, since the initial startup and the database startup are not in there anymore. If you still have the full initial log, that would be really interesting to see.
If not, i have to close this issue even though i would love to understand what was happening, since you are not the first one reporting this.

I will add another hint in the Documentation to make it more clear that this is expected to happen in the beginning :)

**Comment by DuelistRag3** [comment] 2024-10-25 08:37
I´ll just boot it up on my locale dev machine and report back to you, witth a full log asap

**Comment by DuelistRag3** [comment] 2024-10-25 08:56
Okay, on my test machine it actually boots up like instant, have to check it later on the live machine

**Comment by Apfelwurm** [comment] 2024-11-11 19:28
@DuelistRag3 anything else to do here? :)

**Closed** 2024-12-29 17:29 UTC
Labels: question
