### ISSUE TITLE
Display match scoreboard from PugSharp on matchmaking/tournament page

### ISSUE THREAD

**Issue by daniMilio** [Lan2Play/eventula-manager#980] opened 2024-12-14 15:16 UTC
I might be mistaken, but PugSharp has the ability to report back the current scoreboard after each round, as it stores it in the backup files it creates for each match.

It would be awesome if the scoreboard is also shown and stored in Eventula for the current match.

**Comment by Apfelwurm** [comment] 2024-12-14 19:34
This is a duplicate of https://github.com/Lan2Play/eventula-manager/issues/98, so i'm going to close this.

**Closed** 2024-12-14 19:35 UTC
